spring.application.name=eyewear-backend
#avoid conflict between ports
server.port=8080
# ---  MySQL (Docker) ---
spring.datasource.url=jdbc:mysql://localhost:3307/eyewear_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=bXlTdXBlclNlY3JldEtleU15U3VwZXJTZWNyZXRLZXkxMjM=
jwt.expiration=86400000
app.notifications.cleanup-cron=0 0 3 * * *
PAYOS_CLIENT_ID=1a3549f1-3478-4105-a0c4-22771b1c35ab
PAYOS_API_KEY=0baa56f5-26fa-49cf-8a67-862bbf1c5b42
PAYOS_CHECKSUM_KEY=6948a1c8a6cdb82556b339137851caca80d03e3a5def43785d4ed8c487fe3801
