package com.veo.backend.exception;

public enum ErrorCode {
    USER_NOT_FOUND,
    EMAIL_ALREADY_EXIST,
    INVALID_PASSWORD,
    PASSWORD_INCORRECT,
    CONFIRM_PASSWORD_NOT_MATCH,
    ROLE_NOT_FOUND,
    INVALID_ROLE,

    PRODUCT_NOT_FOUND,
    PRODUCT_ALREADY_EXIST,
    PRODUCT_VARIANT_NOT_FOUND,
    PRODUCT_VARIANT_ALREADY_EXIST,
    PRODUCT_VARIANT_OUT_STOCK,
    LENS_PRODUCT_NOT_FOUND,
    LENS_PRODUCT_NOT_VALID,
    CATEGORY_NOT_FOUND,
    CATEGORY_ALREADY_EXIST,
    ORDER_NOT_FOUND,
    PAYMENT_NOT_FOUND,
    PAYMENT_ALREADY_CONFIRMED,
    RETURN_REQUEST_NOT_FOUND,
    APPOINTMENT_NOT_FOUND,
    NOTIFICATION_NOT_FOUND,
    LOCATION_API_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    CONFLICT,
    VALIDATION_ERROR,

    INTERNAL_SERVER_ERROR
}
