package com.veo.backend.exception;

public enum ErrorCode {
    USER_NOT_FOUND,
    EMAIL_ALREADY_EXIST,
    INVALID_PASSWORD,
    PASSWORD_INCORRECT,
    CONFIRM_PASSWORD_NOT_MATCH,
    ROLE_NOT_FOUND,

    PRODUCT_NOT_FOUND,
    PRODUCT_ALREADY_EXIST,
    PRODUCT_VARIANT_NOT_FOUND,
    PRODUCT_VARIANT_ALREADY_EXIST,
    PRODUCT_VARIANT_OUT_STOCK,
    LENS_PRODUCT_NOT_FOUND,

    UNAUTHORIZED,
    FORBIDDEN,
    VALIDATION_ERROR,

    INTERNAL_SERVER_ERROR
}
